<#
.SYNOPSIS
  Start the Client Intelligence Agent for local development.
  Launches backend (uvicorn + hot reload) and frontend (Vite) in separate terminal windows.

.EXAMPLE
  .\run-local.ps1
#>

$ErrorActionPreference = 'Stop'
$Root = $PSScriptRoot

# ── Prerequisite checks ───────────────────────────────────────────────────────
foreach ($cmd in 'python', 'node', 'npm') {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        Write-Error "$cmd not found in PATH. Install it and retry."
    }
}

# ── Load master .env ──────────────────────────────────────────────────────────
$EnvFile = Join-Path $Root '.env'
if (-not (Test-Path $EnvFile)) {
    Write-Error ".env not found. Copy .env.example to .env and fill in values."
}

$Env = @{}
foreach ($line in Get-Content $EnvFile) {
    if ($line -match '^([^#\s][^=]*)=(.*)$') {
        $Env[$Matches[1].Trim()] = $Matches[2].Trim()
    }
}

# ── Helper: read with fallback ────────────────────────────────────────────────
function Get-EnvVar([string]$Key, [string]$Default = '') {
    if ($Env.ContainsKey($Key) -and $Env[$Key] -ne '') { return $Env[$Key] }
    return $Default
}

# ── Validate required vars ────────────────────────────────────────────────────
$LocalMode   = (Get-EnvVar 'LOCAL_MODE' 'false').ToLower()
$BackendPort = Get-EnvVar 'BACKEND_PORT' '8000'

$RequiredAlways = @('COSMOS_ENDPOINT', 'COSMOS_KEY', 'COSMOS_DB_NAME')
$RequiredIfLive = @('AZURE_OPENAI_ENDPOINT', 'AZURE_OPENAI_API_KEY',
                    'AZURE_SEARCH_ENDPOINT', 'AZURE_SEARCH_API_KEY')
$RequiredIfAuth = @('ENTRA_CLIENT_ID', 'ENTRA_TENANT_ID')

$Missing = @()

foreach ($key in $RequiredAlways) {
    if (-not (Get-EnvVar $key)) { $Missing += $key }
}

if ($LocalMode -ne 'true') {
    foreach ($key in $RequiredIfLive) {
        if (-not (Get-EnvVar $key)) { $Missing += $key }
    }
    foreach ($key in $RequiredIfAuth) {
        if (-not (Get-EnvVar $key)) { $Missing += $key }
    }
}

if ($Missing.Count -gt 0) {
    Write-Host ""
    Write-Host "  Missing required .env variables:" -ForegroundColor Red
    foreach ($key in $Missing) { Write-Host "    - $key" -ForegroundColor Red }
    Write-Host ""
    Write-Error "Fix the above values in .env and retry."
}

# ── Inject backend env vars into this process ─────────────────────────────────
# All .env keys are set as process-level env vars so uvicorn inherits them.
foreach ($kv in $Env.GetEnumerator()) {
    Set-Item -Path "env:$($kv.Key)" -Value $kv.Value
}

# ── Write frontend/.env.local ─────────────────────────────────────────────────
# Maps only the vars the frontend actually reads (VITE_ prefix required by Vite).
# Source of truth for which vars the frontend needs: src/auth/ and src/hooks/.
$FrontendEnvFile = Join-Path $Root 'frontend\.env.local'

@(
    "# Auto-generated by run-local.ps1 — do not edit manually"
    ""
    "# Auth (MSAL)"
    "VITE_ENTRA_CLIENT_ID=$(Get-EnvVar 'ENTRA_CLIENT_ID')"
    "VITE_ENTRA_TENANT_ID=$(Get-EnvVar 'ENTRA_TENANT_ID')"
    ""
    "# API"
    "VITE_BACKEND_URL=http://localhost:$BackendPort"
    ""
    "# Mode"
    "VITE_LOCAL_MODE=$LocalMode"
) | Set-Content $FrontendEnvFile -Encoding UTF8

# ── Python venv ───────────────────────────────────────────────────────────────
$VenvDir    = Join-Path $Root 'backend\.venv'
$PipExe     = Join-Path $VenvDir 'Scripts\pip.exe'
$UvicornExe = Join-Path $VenvDir 'Scripts\uvicorn.exe'
$ReqFile    = Join-Path $Root 'backend\requirements.txt'
$StampFile  = Join-Path $VenvDir '.req.stamp'

if (-not (Test-Path (Join-Path $VenvDir 'Scripts\python.exe'))) {
    Write-Host "Creating Python virtual environment..." -ForegroundColor Cyan
    python -m venv $VenvDir
}

$ReqHash = (Get-FileHash $ReqFile -Algorithm MD5).Hash
if (-not (Test-Path $StampFile) -or (Get-Content $StampFile -Raw).Trim() -ne $ReqHash) {
    Write-Host "Installing backend dependencies..." -ForegroundColor Cyan
    & $PipExe install -r $ReqFile -q
    Set-Content $StampFile -Value $ReqHash -Encoding UTF8
}

# ── npm install ───────────────────────────────────────────────────────────────
if (-not (Test-Path (Join-Path $Root 'frontend\node_modules'))) {
    Write-Host "Installing frontend dependencies..." -ForegroundColor Cyan
    Push-Location (Join-Path $Root 'frontend')
    npm install --silent
    Pop-Location
}

# ── Launch backend ────────────────────────────────────────────────────────────
$BackendCmd = "`$env:PYTHONPATH = '$Root\backend'; & '$UvicornExe' app.main:app --reload --host 127.0.0.1 --port $BackendPort"
Start-Process powershell -ArgumentList '-NoExit', '-Command', $BackendCmd -WorkingDirectory $Root

# ── Launch frontend ───────────────────────────────────────────────────────────
Start-Process powershell -ArgumentList '-NoExit', '-Command', 'npm run dev' `
    -WorkingDirectory (Join-Path $Root 'frontend')

# ── Summary ───────────────────────────────────────────────────────────────────
$ModeLabel    = if ($LocalMode -eq 'true') { 'LOCAL (no auth, stub AI)' } else { 'LIVE (Entra ID + Azure)' }
$RerankLabel  = if ((Get-EnvVar 'RERANK_ENABLED' 'false') -eq 'true') { 'on' } else { 'off' }
$ChunkLabel   = if ((Get-EnvVar 'SEMANTIC_CHUNKING' 'false') -eq 'true') { 'semantic' } else { 'fixed' }

Write-Host ""
Write-Host "  Services starting in separate windows." -ForegroundColor Green
Write-Host ""
Write-Host "  Frontend : http://localhost:5173"
Write-Host "  Backend  : http://localhost:$BackendPort"
Write-Host "  API docs : http://localhost:$BackendPort/docs"
Write-Host ""
Write-Host "  Mode     : $ModeLabel"
Write-Host "  Rerank   : $RerankLabel"
Write-Host "  Chunking : $ChunkLabel"
Write-Host "  OneDrive : $(Get-EnvVar 'ONEDRIVE_SYNC_PATH' '(not set)')"
Write-Host ""
Write-Host "  frontend/.env.local written with $(((Get-Content $FrontendEnvFile) | Where-Object { $_ -match '^VITE_' }).Count) VITE_ vars"
Write-Host ""
Write-Host "  Close those windows to stop the services." -ForegroundColor DarkGray
